function parsave_rho_B0(output_fullpath, alpha_update, rho_norm, fB0_norm, residual_norm, rho_final, fB0_final, scale_factor, w_fB0, h_fB0, alpha_min, irgnm_iterations, slice_nr, computation_time)
save(output_fullpath, 'alpha_update', 'rho_norm', 'fB0_norm', 'residual_norm', ...
     'rho_final', 'fB0_final', 'scale_factor', 'w_fB0', 'h_fB0', 'alpha_min', ...
     'irgnm_iterations', 'slice_nr', 'computation_time', '-v7.3');
end